### ISSUE TITLE
iOS Profiles don’t work + Encrypted Malware blocking

### ISSUE THREAD

**Issue by SUICIDEB0YS** [mullvad/encrypted-dns-profiles#1]
Hi, when I try to install the adblocking profiles it says „unknown error“ and I can’t install it. Extended HTTPS works, others I didn’t test.

And is there a way to have encrypted DNS of 100.64.0.7 - Ad blocking, tracker blocking and malware blocking? So that this can be used in Browsers or for profiles?

**Comment by jbjorkang** [comment]
Please try again, things might have changed since.

We have plans for other DNS blocking in the future.
