### ISSUE TITLE
When using profile device cannot connect to internet

### ISSUE THREAD

**Issue by CloudRealm** [mullvad/encrypted-dns-profiles#10]
https://github.com/mullvad/encrypted-dns-profiles/blob/main/base/mullvad-encrypted-dns-https-base.mobileconfig
https://github.com/mullvad/encrypted-dns-profiles/blob/main/base/mullvad-encrypted-dns-tls-base.mobileconfig

Both do not work, I have not tested the rest of the profiles, but I think they do not work.

**Comment by jbjorkang** [comment]
Please contact our Support Team by email in case there are other issues present: 

support at mullvadvpn dot net
