### ISSUE TITLE
Expired cert on blog post config files

### ISSUE THREAD

**Issue by GrapeBacon** [mullvad/encrypted-dns-profiles#2]
Just a heads up that a certificate on your linked blog configs has expired. https://mullvad.net/en/blog/2023/2/28/profiles-to-configure-our-encrypted-dns-on-apple-devices/

![IMG_2017](https://github.com/mullvad/encrypted-dns-profiles/assets/91326615/dbb7b21e-4350-4669-a618-c1db06a08db0)

You might want to change the blog post links.

**Comment by jbjorkang** [comment]
Thanks, I'll be sure to have it updated

**Comment by jbjorkang** [comment]
Thanks, I'll be sure to have it updated. Have you tried redownloading them? I refreshed them a few days ago

**Comment by GrapeBacon** [comment]
Yep, I grabbed one fresh from GitHub here and it worked great.
